# Generated by Django 6.0.3 on 2026-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('UPLOAD_VIDEO', 'Upload Tutorial Video'), ('UPLOAD_AUDIO', 'Upload Audio Lesson'), ('TEACH_SESSION', 'Teach Skill Session'), ('HELP_LEARNER', 'Help Another Learner'), ('BOOK_SESSION', 'Book Learning Session'), ('COURSE_PURCHASE', 'Purchase Course'), ('LANG_SESSION', 'Language Session'), ('AI_LESSON', 'AI Language Lesson'), ('REFERRAL', 'Referral Bonus'), ('ADMIN_AWARD', 'Admin Award')], max_length=20),
        ),
    ]
