# Generated by Django 6.0.3 on 2026-03-12 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('el', 'Greek'), ('pl', 'Polish'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('ms', 'Malay'), ('uk', 'Ukrainian')], max_length=5)),
                ('credits_paid', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_sessions_learning', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_sessions_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('el', 'Greek'), ('pl', 'Polish'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('ms', 'Malay'), ('uk', 'Ukrainian')], max_length=5)),
                ('role', models.CharField(choices=[('TEACH', 'Teach'), ('LEARN', 'Learn')], max_length=5)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], default='Intermediate', max_length=20)),
                ('hourly_credits', models.IntegerField(default=20, help_text='Credits per 1-hour session')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'language', 'role')},
            },
        ),
    ]
