# Generated by Django 6.0.3 on 2026-03-12 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('el', 'Greek'), ('pl', 'Polish'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('ms', 'Malay'), ('uk', 'Ukrainian')], max_length=5)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('conversation', 'Conversation Practice'), ('vocabulary', 'Vocabulary Training')], default='beginner', max_length=20)),
                ('credits_spent', models.IntegerField(default=10)),
                ('message_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Tutor')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='languages.aitutorsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('el', 'Greek'), ('pl', 'Polish'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('ms', 'Malay'), ('uk', 'Ukrainian')], max_length=5)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('vocab_learned', models.IntegerField(default=0)),
                ('ai_sessions', models.IntegerField(default=0)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('last_studied', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_studied'],
                'unique_together': {('user', 'language')},
            },
        ),
    ]
