services:
  - type: web
    name: skillswapp
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: "bash build.sh"
    startCommand: "gunicorn --workers 3 --bind 0.0.0.0:$PORT peer_skill_swap.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        scope: runtime
        sync: false
      - key: PORT
        value: "10000"

databases:
  - name: skillswapp_db
    databaseName: skillswapp_db
    user: skillswapp_user
    region: singapore
    plan: free
