# Generated by Django 6.0.3 on 2026-03-12 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits_earned', models.IntegerField(default=0)),
                ('total_credits_spent', models.IntegerField(default=0)),
                ('current_credits', models.IntegerField(default=0)),
                ('sessions_taught', models.IntegerField(default=0)),
                ('sessions_learned', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('skills_offered', models.IntegerField(default=0)),
                ('skills_learned', models.IntegerField(default=0)),
                ('videos_uploaded', models.IntegerField(default=0)),
                ('audio_uploaded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaderboards',
                'ordering': ['-total_credits_earned', '-sessions_taught', '-average_rating'],
            },
        ),
    ]
