# Generated by Django 6.0.3 on 2026-03-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_category_skill_difficulty_audiolesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
