# Generated by Django 6.0.3 on 2026-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'New Message'), ('SESSION_REQUEST', 'Session Request'), ('SESSION_ACCEPTED', 'Session Accepted'), ('SESSION_REJECTED', 'Session Rejected'), ('CREDITS_EARNED', 'Credits Earned'), ('MATCH_FOUND', 'Match Found'), ('REVIEW_RECEIVED', 'Review Received'), ('FRIEND_REQUEST', 'Friend Request'), ('FRIEND_ACCEPTED', 'Friend Request Accepted'), ('SYSTEM', 'System Notification')], max_length=20),
        ),
    ]
